### ISSUE TITLE
task/addCORSConfiguration

### ISSUE THREAD

**Issue by philippkuehling** [Doma1612/video-portal-backend#5]
Hi,

es müsste noch die CORS-Konfuguration im Backend eingestellt werden, damit ich HTTP-Requests auf die Endpunkte absetzen darf vom Frontend. Das war zumindest ein Problem bei mir in Verteilte Systeme. Den Code würde ich hierzu noch einstellen.

**Comment by Doma1612** [comment]
Was genau meinst du? Das musste ich in meiner HA nicht machen.

**Comment by philippkuehling** [comment]
Im Browser gab es bei mir Probleme (bei anderen auch) die Endpunkte aufzurufen. CORS blockiert das teilweise zur Sicherheit.

**Comment by philippkuehling** [comment]
@Doma1612 CORS wurde implementiert
